### ISSUE TITLE
Possible Mobi Version?

### ISSUE THREAD

**Issue by thelittlewonder** [derek-knox/Coding-For-Designers#2]
Hi @derek-knox :-) 

Just discovered the book. Is there any Mobi version so that I can read this on my Kindle?

**Comment by derek-knox** [comment]
There is not one currently but I'm authoring in markdown so Mobi is an output option. This isn't a focus for now as two more chapters need to be completed first. Once complete a mobi version will likely see the light of day.

**Comment by thelittlewonder** [comment]
No problem 👍 I will keep an eye! Wish you luck :-)
